[package]
name = "broadcast"
version = "0.1.0"
edition = "2024"

[dependencies]
node.workspace = true

tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true

[lints]
workspace = true
