[package]
name = "grow-only-counter"
version = "0.1.0"
edition = "2024"


[dependencies]
node.workspace = true

tokio = { workspace = true, features = ["full"] }
env_logger.workspace = true
log.workspace = true
serde_json.workspace = true

[lints]
workspace = true

